export const CHANGE_INPUT = 'changeInput'//监听输入框值变化
export const CHANGE_INPUT1 = 'changeInput1'//监听输入框值变化
export const CHANGE_INPUT2 = 'changeInput2'//监听输入框值变化
export const CHANGE_INPUT3 = 'changeInput3'//监听输入框值变化
export const CHANGE_INPUT4 = 'changeInput4'//监听输入框值变化
export const CHANGE_INPUT5 = 'changeInput5'//监听输入框值变化
export const CHANGE_INPUT6 = 'changeInput6'//监听输入框值变化
export const CHANGE_INPUT7 = 'changeInput7'//监听输入框值变化
export const CHANGE_INPUT8 = 'changeInput8'//监听输入框值变化
export const CHANGE_INPUT9 = 'changeInput9'//监听输入框值变化
export const CHANGE_INPUT10 = 'changeInput10'//监听输入框值变化
export const CHANGE_INPUT11 = 'changeInput11'//监听输入框值变化
export const CHANGE_INPUT12 = 'changeInput12'//监听输入框值变化
export const CHANGE_INPUT13 = 'changeInput13'//监听输入框值变化
export const ADD_ITEM = 'addItem'//增加=>列表增加使用
export const ADD_ITEM1 = 'addItem1'//增加=>列表增加使用
export const ADD_ITEM2 = 'addItem2'//增加=>列表增加使用
export const POST_ITEM = 'postItem'//增
export const DELETE_ITEM = 'deleteItem'//删
export const PUT_ITEM = 'putItem'//改
export const GET_LIST = 'getItem'//查
export const GET_LIST1 = 'getItem1'//查
export const GET_LIST2 = 'getItem2'//查
export const GET_LIST3 = 'getItem3'//查
export const GET_LIST4 = 'getItem4'//查
export const GET_LIST5 = 'getItem5'//查
export const GET_LIST6 = 'getItem6'//查
export const GET_LIST7 = 'getItem7'//查
export const GET_LIST8 = 'getItem8'//查
export const GET_LIST9 = 'getItem9'//查
export const GET_LIST10 = 'getItem10'//查
export const GET_LIST11 = 'getItem11'//查
export const GET_LIST12 = 'getItem12'//查

