export default stateToProps = (state) => {
    return {
        inputValue: state.inputValue,
        inputValue1: state.inputValue1,
        inputValue2: state.inputValue2,
        inputValue3: state.inputValue3,
        inputValue4: state.inputValue4,
        inputValue5: state.inputValue5,
        inputValue6: state.inputValue6,
        inputValue7: state.inputValue7,
        inputValue8: state.inputValue8,
        inputValue9: state.inputValue9,
        inputValue10: state.inputValue10,
        inputValue11: state.inputValue11,
        inputValue12: state.inputValue12,
        inputValue13: state.inputValue13,
        list: state.list,
        list1: state.list1,
        list2: state.list2,
        data: state.data,
        data1: state.data1,
        data2: state.data2,
        data3: state.data3,
        data4: state.data4,
        data5: state.data5,
        data6: state.data6,
        data7: state.data7,
        data8: state.data8,
        data9: state.data9,
        data10: state.data10,
        data11: state.data11,
        data12: state.data12,
        post: state.post,//没啥用
        // delete:state.delete//没啥用
    }
}